import type { CareEscalation, CareObservation } from "@/domain/care/types";

export interface EscalationPatient {
  name?: string | null;
  email?: string | null;
  medication?: string | null;
  currentDose?: string | null;
}

export interface EscalationEmail {
  subject: string;
  text: string;
  html: string;
}

function formatList(items: string[]): string {
  return items.map((s) => s.replace(/_/g, " ")).join(", ");
}

function formatSeverity(severity: string): string {
  return severity.charAt(0).toUpperCase() + severity.slice(1);
}

function medicationResource(medication?: string | null): { label: string; url: string } | null {
  if (!medication) return null;
  const m = medication.toLowerCase();
  if (m.includes("tirzepatide")) {
    return { label: "Mounjaro / Zepbound (tirzepatide) — Drugs.com", url: "https://www.drugs.com/mounjaro.html" };
  }
  if (m.includes("semaglutide")) {
    return { label: "Ozempic / Wegovy / Rybelsus (semaglutide) — Drugs.com", url: "https://www.drugs.com/ozempic.html" };
  }
  if (m.includes("liraglutide")) {
    return { label: "Saxenda / Victoza (liraglutide) — Drugs.com", url: "https://www.drugs.com/saxenda.html" };
  }
  if (m.includes("dulaglutide")) {
    return { label: "Trulicity (dulaglutide) — Drugs.com", url: "https://www.drugs.com/trulicity.html" };
  }
  if (m.includes("exenatide")) {
    return { label: "Byetta / Bydureon (exenatide) — Drugs.com", url: "https://www.drugs.com/byetta.html" };
  }
  return { label: "GLP-1 medications — Drugs.com", url: "https://www.drugs.com/drug-class/incretin-mimetics.html" };
}

export function buildEscalationEmail(
  escalation: CareEscalation,
  observation: CareObservation,
  patient: EscalationPatient,
  siteUrl = "https://bodydebt.thisyearnofear.com",
): EscalationEmail {
  const dashboardUrl = `${siteUrl}/care/clinician`;
  const patientLabel = patient.name || patient.email || "A patient";
  const patientIdentifier = patient.name && patient.email
    ? `${patient.name} (${patient.email})`
    : patient.name || patient.email || escalation.patientId;
  const medicationLine = patient.medication
    ? `${patient.medication}${patient.currentDose ? ` — ${patient.currentDose}` : ""}`
    : "Not recorded";
  const resource = medicationResource(patient.medication);
  const checkedInAt = observation.checkInAt.toLocaleString();

  const subject = `Escalation: ${formatList(observation.symptoms)} (${observation.symptomSeverity}) — ${patientLabel}`;

  const redFlags = [
    "Persistent vomiting with signs of dehydration",
    "Severe or worsening abdominal pain",
    "Jaundice, dark urine, or pale stools",
    "Difficulty breathing or swallowing",
    "Signs of allergic reaction (hives, swelling, wheezing)",
  ];

  const text =
    `Hi Care Team,\n\n` +
    `${patientIdentifier} just submitted a GLP-1 check-in that requires clinical review.\n\n` +
    `Reported symptom(s): ${formatList(observation.symptoms)}\n` +
    `Severity: ${formatSeverity(observation.symptomSeverity)}\n` +
    `Medication & dose: ${medicationLine}\n` +
    `Adherence: ${observation.adherence.replace(/_/g, " ")}\n` +
    (observation.notes ? `Patient notes: ${observation.notes}\n` : "") +
    `Checked in: ${checkedInAt}\n\n` +
    `What to do next\n` +
    `1. Review the check-in in the Care Companion dashboard: ${dashboardUrl}\n` +
    `2. Contact the patient if you need more information.\n` +
    `3. If symptoms are severe or worsening, advise the patient to seek urgent or emergency care.\n\n` +
    `When to recommend urgent / emergency care\n` +
    redFlags.map((r) => `• ${r}`).join("\n") +
    `\n\n` +
    (resource ? `Trusted resource\n• ${resource.label}: ${resource.url}\n\n` : "") +
    `This escalation was generated by Body Debt Care Companion. It does not replace clinical judgment.\n\n` +
    `Escalation ID: ${escalation.id}\n` +
    `Patient ID: ${escalation.patientId}\n` +
    `Observed at: ${checkedInAt}`;

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${subject}</title>
</head>
<body style="margin:0; padding:0; background:#f7f7f7; font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#1f1f1f;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f7f7f7; padding:24px 0;">
    <tr>
      <td align="center">
        <table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0" style="background:#ffffff; border-radius:12px; overflow:hidden; max-width:640px; width:100%;">
          <tr>
            <td style="background:#0f172a; padding:24px 32px; text-align:left;">
              <h1 style="margin:0; color:#ffffff; font-size:20px; font-weight:600; letter-spacing:-0.2px;">Body Debt Care Companion</h1>
              <p style="margin:4px 0 0; color:#94a3b8; font-size:13px;">Escalation notification</p>
            </td>
          </tr>
          <tr>
            <td style="padding:32px;">
              <p style="margin:0 0 16px; font-size:16px; line-height:1.5;">Hi Care Team,</p>
              <p style="margin:0 0 24px; font-size:16px; line-height:1.5;"><strong>${patientIdentifier}</strong> just submitted a GLP-1 check-in that requires clinical review.</p>

              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f8fafc; border:1px solid #e2e8f0; border-radius:10px; margin:0 0 24px;">
                <tr>
                  <td style="padding:20px;">
                    <p style="margin:0 0 8px; font-size:14px; color:#64748b;">Symptom(s)</p>
                    <p style="margin:0 0 16px; font-size:16px; font-weight:600;">${formatList(observation.symptoms)}</p>

                    <p style="margin:0 0 8px; font-size:14px; color:#64748b;">Severity</p>
                    <p style="margin:0 0 16px; font-size:16px; font-weight:600; color:${observation.symptomSeverity === "severe" ? "#dc2626" : "#ea580c"};">${formatSeverity(observation.symptomSeverity)}</p>

                    <p style="margin:0 0 8px; font-size:14px; color:#64748b;">Medication & dose</p>
                    <p style="margin:0 0 16px; font-size:16px; font-weight:600;">${medicationLine}</p>

                    <p style="margin:0 0 8px; font-size:14px; color:#64748b;">Adherence</p>
                    <p style="margin:0; font-size:16px; font-weight:600;">${observation.adherence.replace(/_/g, " ")}</p>
                    ${observation.notes ? `<p style="margin:16px 0 0; font-size:14px; color:#64748b;">Patient notes</p><p style="margin:4px 0 0; font-size:15px; color:#1e293b;">${observation.notes}</p>` : ""}
                  </td>
                </tr>
              </table>

              <h2 style="margin:0 0 12px; font-size:16px; font-weight:600; color:#0f172a;">What to do next</h2>
              <ol style="margin:0 0 24px; padding-left:20px; font-size:15px; line-height:1.6;">
                <li style="margin-bottom:8px;">Review the check-in in the <a href="${dashboardUrl}" style="color:#2563eb; text-decoration:underline;">Care Companion dashboard</a>.</li>
                <li style="margin-bottom:8px;">Contact the patient if you need more information.</li>
                <li>If symptoms are severe or worsening, advise the patient to seek urgent or emergency care.</li>
              </ol>

              <h2 style="margin:0 0 12px; font-size:16px; font-weight:600; color:#0f172a;">When to recommend urgent / emergency care</h2>
              <ul style="margin:0 0 24px; padding-left:20px; font-size:15px; line-height:1.6; color:#334155;">
                ${redFlags.map((r) => `<li style="margin-bottom:6px;">${r}</li>`).join("")}
              </ul>

              ${resource ? `
              <h2 style="margin:0 0 10px; font-size:16px; font-weight:600; color:#0f172a;">Trusted resource</h2>
              <p style="margin:0 0 24px; font-size:15px; line-height:1.5;">
                <a href="${resource.url}" style="color:#2563eb; text-decoration:underline;">${resource.label}</a>
              </p>
              ` : ""}

              <p style="margin:24px 0 0; padding-top:24px; border-top:1px solid #e2e8f0; font-size:13px; line-height:1.5; color:#64748b;">
                This escalation was generated by Body Debt Care Companion. It is a decision-support tool and does not replace clinical judgment.
              </p>

              <p style="margin:16px 0 0; font-size:12px; line-height:1.5; color:#94a3b8;">
                Escalation ID: ${escalation.id}<br />
                Patient ID: ${escalation.patientId}<br />
                Observed at: ${checkedInAt}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();

  return { subject, text, html };
}
